package com.yty;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
@SpringBootApplication
public class Springsecurity006Url {

    public static void main(String[] args) {
        SpringApplication.run(Springsecurity006Url.class, args);
    }

}
