package com.yty;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@MapperScan("com.yty.dao")
@ComponentScan("com")
public class Springsecurity011DatabaseAuthenticationApplication {

    public static void main(String[] args) {
        SpringApplication.run(Springsecurity011DatabaseAuthenticationApplication.class, args);
    }

}
